---
title: "scTACseq_merge_CellsPeaksStatistics"
author: "Laëtitia Racine"
date: "2022-09-06"
subtitle: "Dernière modification : `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: "hide"
    toc: true
    toc_float: false
---

```{r, Setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

```{r, Dependencies, warning=F, message=F}

library(ggplot2)
library(Seurat)
library(dplyr)
library(tidyverse)
library(kableExtra)

```

```{r, Working directories and external script}

directory = "/home/rparmentier/Bureau/Git_Metabo_Analysis/"
directory_exp = paste0(directory, "exp/")
directory_data = paste0(directory, "data/scATACseq/")
directory_bin = paste0(directory, "bin/")

# Create a unique folder for output corresponding to the date of the day
current_date = format(Sys.time(), "%Y%m%d")
dir.create(path = paste0(directory_exp,"scTACseq_merge_CellsPeaksStatistics/"))
dir.create(path = paste0(directory_exp,"scTACseq_merge_CellsPeaksStatistics/", current_date))
directory_output = paste0(directory_exp, "scTACseq_merge_CellsPeaksStatistics/", current_date, "/")

# Load external script with functions and constantes 
source(file = paste0(directory_bin, "functions_constantes.R"))

```

Work with only merged object with common list of peaks => change manually if you want with other file

```{r, Input loading, message=F}

dir = pic_last_dir(paste0(directory_exp, "scATACseq_merge_NormalizationReduction/"))
seurat_obj = readRDS(paste0(dir, "/", "seurat_common_merged_qc_normalized_reduced.rds"))

number_conditions = length(unique(seurat_obj$orig.ident))
conditions = unique(seurat_obj$orig.ident)
  
```


# Peaks detected VS peaks no detected

```{r, Count matrix to binary matrix}

matrix_seurat = GetAssayData(seurat_obj, slot = "data")

stat_tab_cell = list()
stat_tab_peak = list()

for (i in 1:number_conditions) { # très très long

  cat(conditions[i], "on going")
  
  # extract matrix for one condition and turn it into binary 1/0 matrix
  tab = matrix_seurat[ , grepl(pattern = conditions[i], colnames(matrix_seurat))]
  tab = as.matrix(tab)
  tab = as.data.frame(tab)
  tab[tab > 0] = 1
  
  # sum per row to have the number of cells with the peak
  tab_peak = as.data.frame(rowSums(tab))
  colnames(tab_peak) = paste0(conditions[i], "_CellsSharingThisPeak")
  tab_peak$Peak_name = rownames(tab_peak)

  # sum per column to have the number of peaks for each cell 
  tab_cell = as.data.frame(colSums(tab))
  colnames(tab_cell) = "NbPeaksInThisCell"
  tab_cell$Cell_name = rownames(tab_cell)
  tab_cell$Condition = conditions[i]

  # store results 
  stat_tab_peak[[conditions[i]]] = tab_peak
  stat_tab_cell[[conditions[i]]] = tab_cell
  
}

global_tab_peak = stat_tab_peak %>% 
  purrr::reduce(full_join, by = "Peak_name") %>%
  dplyr::relocate(Peak_name)
global_tab_cell = do.call("rbind", stat_tab_cell)

```


# How many peaks per cell

```{r, Number of peaks per cell, results = 'hold',  fig.width = 12, fig.height = 10}

# Histogram of number of peaks per cell
plot_nbpeaks_cell = ggplot(data = global_tab_cell, aes(x = NbPeaksInThisCell, fill = Condition)) +
  geom_histogram(binwidth = 500, color = "black", alpha = 0.5) +
  scale_fill_manual(values = color_code, limits = force) +
  facet_wrap(facets = .~Condition) +
  ylab(label = "Cell number") +
  xlab(label = "Peak number") +
  ggtitle(label = "Number of peaks in the cells - distribution (binwidth = 500)") 
plot_nbpeaks_cell

# Statistics of histogram
tab_stat_cell = global_tab_cell %>% 
  dplyr::group_by(Condition) %>%
  dplyr::mutate(Condition = Condition,
                Total_nbcells_studied = n(),
                Min_nbpeaks_per_cell = min(NbPeaksInThisCell),
                Mean_nbpeaks_per_cell = mean(NbPeaksInThisCell),
                Median_nbpeaks_per_cell = median(NbPeaksInThisCell),
                Max_nbpeaks_per_cell = max(NbPeaksInThisCell),
                Nbcell_with_nbpeaks_inf_10000 = length(NbPeaksInThisCell[NbPeaksInThisCell < 10000]),
                Nbcell_with_nbpeaks_btw_10000_20000 = length(NbPeaksInThisCell[NbPeaksInThisCell >= 10000 & NbPeaksInThisCell < 20000]),
                Nbcell_with_nbpeaks_btw_20000_30000 = length(NbPeaksInThisCell[NbPeaksInThisCell >= 20000 & NbPeaksInThisCell < 30000]),
                Nbcell_with_nbpeaks_sup_30000 = length(NbPeaksInThisCell[NbPeaksInThisCell >= 30000])
                ) %>%
  dplyr::select(-Cell_name, -NbPeaksInThisCell) %>%
  dplyr::distinct()

tab_stat_cell %>%
  kable() %>%
  kable_styling()

```


# How much the peaks are shared among cells 

```{r, Number of peaks shared by the cells, results = hold, fig.width = 12, fig.height = 10}

# Reorganize tab 
global_tab_peak_long = global_tab_peak %>%
  tidyr::pivot_longer(cols = c(2:ncol(global_tab_peak)),
                      names_to = "Condition",
                      values_to = "CellsSharingThisPeak") %>%
  dplyr::mutate(Condition = str_extract(string = Condition, pattern = "[:alnum:]+(?=_)"))

## Histogram of number of peaks (= freq) shared by n cells
plot_nbcells_sharing_peak = ggplot(data = global_tab_peak_long, aes(x = CellsSharingThisPeak, fill = Condition)) +
  geom_histogram(binwidth = 50, color = "black", alpha = 0.5) +
  scale_fill_manual(values = color_code, limits = force) +
  facet_wrap(facets = .~Condition) +
  ylab(label = "Peak number") +
  xlab(label = "Cell Number") +
  ggtitle(label = "Number of cells sharing the same peak - distribution (binwidth = 50)") 
plot_nbcells_sharing_peak

# Statistics of histogram
tab_stat_peak = global_tab_peak_long %>% 
  dplyr::group_by(Condition) %>%
  dplyr::mutate(Condition = Condition,
                Min_nbcells_sharing_the_peak = min(CellsSharingThisPeak),
                Mean_nbcells_sharing_the_peak = mean(CellsSharingThisPeak),
                Median_nbcells_sharing_the_peak = median(CellsSharingThisPeak),
                Max_nbcells_sharing_the_peak = max(CellsSharingThisPeak),
                Nbpeaks_shared_by_inf_1000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak < 1000]),
                Nbpeaks_shared_by_btw_1000_2000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak >= 1000 & CellsSharingThisPeak < 2000]),
                Nbpeaks_shared_by_btw_2000_3000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak >= 2000 & CellsSharingThisPeak < 3000]),
                Nbpeaks_shared_by_btw_3000_4000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak >= 3000 & CellsSharingThisPeak < 4000]),
                Nbpeaks_shared_by_sup_4000_5000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak >= 4000 & CellsSharingThisPeak < 5000]),
                Nbpeaks_shared_by_sup_5000_cells = length(CellsSharingThisPeak[CellsSharingThisPeak >= 5000])
                ) %>%
  dplyr::select(-Peak_name, -CellsSharingThisPeak) %>%
  dplyr::distinct()

tab_stat_peak %>%
  knitr::kable() %>%
  kableExtra::kable_styling()

```

```{r, Save}

write.csv2(x = global_tab_cell, file = paste0(directory_output, "global_tab_cell.csv"))
write.csv2(x = tab_stat_cell, file = paste0(directory_output, "statistic_tab_cell.csv"))
ggsave(plot = plot_nbpeaks_cell, filename = paste0(directory_output, "nbpeaks_per_cell_plot.svg"))

write.csv2(x = global_tab_peak, file = paste0(directory_output, "global_tab_peak.csv"))
write.csv2(x = tab_stat_cell, file = paste0(directory_output, "statistic_tab_peak.csv"))
ggsave(plot = plot_nbpeaks_cell, filename = paste0(directory_output, "nbcell_sharing_peaks_plot.svg"))

```


```{r, Rsession}

rm(list = ls())
sessionInfo()

```


  