---
title: "scRNAseq_CITEseq_IntegrateConditions"
author: "Laëtitia Racine"
date: "2022-09-26"
subtitle: "Dernière modification : `r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: "show"
    toc: false
    theme: journal
---


```{r, Setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, Dependencies, message=F, warning=F}

library(Seurat)
library(SeuratData)
library(dplyr)

# devtools::install_github('satijalab/seurat-data')

```

# Objectif du code 

Ce code **permet de** :  
- fusionner les objets Seurat pour obtenir un seul objet contenant tout le dataset  
- enregistrer l'objet Seurat global  

Il s'est **inspiré** de :   
- https://github.com/satijalab/seurat/issues/1787   
- https://github.com/stuart-lab/signac/issues/197  
- https://www.biostars.org/p/9516696/  
- https://satijalab.org/seurat/articles/integration_introduction.html 
- https://satijalab.org/seurat/reference/prepsctintegration


```{r, Working directories and external script, warning=F, message=F}

directory = "/home/rparmentier/Bureau/Git_Metabo_Analysis/"
directory_exp = paste0(directory, "exp/")
directory_data = paste0(directory, "data/scRNAseq/")
directory_bin = paste0(directory, "bin/")

# Create a unique folder for output corresponding to the date of the day
# current_date = format(Sys.time(), "%Y%m%d")
current_date = "20221007"
dir.create(path = paste0(directory_exp,"scRNAseq_CITEseq_integ_IntegrateConditions/"))
dir.create(path = paste0(directory_exp,"scRNAseq_CITEseq_integ_IntegrateConditions/", current_date))
directory_output = paste0(directory_exp, "scRNAseq_CITEseq_integ_IntegrateConditions/", current_date, "/")

# Load external script with functions and constantes 
source(file = paste0(directory_bin, "functions_constantes.R"))

```

```{r, Input loading}

dir = pic_last_dir(paste0(directory_exp, "scRNAseq_CITEseq_ind_NormalizeData/"))

# Object with cc regression
list_seurat_obj_cc = readRDS(paste0(dir, "/", "list_seurat_obj_qc_norm_ccr.rds"))
# Object without cc regression
list_seurat_obj = readRDS(paste0(dir, "/", "list_seurat_obj_qc_norm.rds"))

```

```{r, Merge files from same experiment}

merge_manip_metabo = function(list_obj) {
  
  # Merge files from the first experiment and redo scaling
  cond_manip1 = c("CTRL", "CTRLaK", "DON", "DONaK", "2DG", "2DGaK", "VPA")
  list_manip1 = c(list_obj[["CTRLaK"]], list_obj[["DON"]],
                  list_obj[["DONaK"]], list_obj[["2DG"]],
                  list_obj[["2DGaK"]], list_obj[["VPA"]])
  merge_seurat_obj1 = merge(x = list_obj[["CTRL"]], y = list_manip1,
                            add.cell.ids = cond_manip1, merge.data = TRUE)
  
  # Merge files from the second experiment
  cond_manip2 = c("CTRL2", "AOA", "AOAaK")
  list_manip2 = c(list_obj[["AOA"]], list_obj[["AOAaK"]])
  merge_seurat_obj2 = merge(x = list_obj[["CTRL2"]], y = list_manip2,
                            add.cell.ids = cond_manip2, merge.data = TRUE)
  
  # Stocker les deux manipulations dans une liste 
  list_merged_obj = list("manip1" = merge_seurat_obj1,
                         "manip2" = merge_seurat_obj2)
  
  # output of the function
  return(list_merged_obj)
  
}

merged_list_seurat_obj = merge_manip_metabo(list_seurat_obj)
merged_list_seurat_obj = lapply(merged_list_seurat_obj, function(x) {
  DefaultAssay(x) = "SCT"
  x = ScaleData(x)
  DefaultAssay(x) = "RNA"
  x = ScaleData(x)
})

merged_list_seurat_obj_cc = merge_manip_metabo(list_seurat_obj_cc)
merged_list_seurat_obj_cc = lapply(merged_list_seurat_obj_cc, function(x) {
  DefaultAssay(x) = "SCT"
  x = ScaleData(x)
  DefaultAssay(x) = "RNA"
  x = ScaleData(x)
})

saveRDS(merged_list_seurat_obj, paste0(directory_output, "merged_list_seurat_obj.rds"))
saveRDS(merged_list_seurat_obj_cc, paste0(directory_output, "merged_list_seurat_obj_cc.rds"))

```


```{r}

merged_list_seurat_obj = readRDS(paste0(directory_output, "merged_list_seurat_obj.rds"))
merged_list_seurat_obj_cc = readRDS(paste0(directory_output, "merged_list_seurat_obj_cc.rds"))

```



https://satijalab.org/seurat/articles/integration_rpca.html
RPCA semble plus adapté dans notre cas pour éviter la "overcorrection"

```{r, Integration RPCA sur LogNorm}

integ_rpca_fun = function(list_obj, number_conditions) {

  # choose RNA assay as default assay for each object
  for (i in 1:number_conditions) {DefaultAssay(list_obj[[i]]) = "RNA"}
  # select features that are repeatedly variable across datasets for integration
  features = SelectIntegrationFeatures(object.list = list_obj,
                                       nfeatures = 2000, 
                                       assay = rep("RNA", number_conditions),
                                       verbose = TRUE)
  # run PCA to be able to apply rpca for integration
  list_obj = lapply(X = list_obj, FUN = RunPCA, features = features)
  # identify anchors to integrate the datasets
  anchors = FindIntegrationAnchors(object.list = list_obj,
                                   assay = rep("RNA", number_conditions),
                                   anchor.features = features,
                                   normalization.method = "LogNormalize",
                                   reduction = "rpca",
                                   verbose = TRUE)
  # create an integrated data assay in the object
  list_obj = IntegrateData(anchorset = anchors, 
                           new.assay.name = "integrated.log",
                           normalization.method = "LogNormalize",
                           verbose = TRUE)
  # return output
  return(list_obj)
  
}

merged_list_seurat_obj_rpcalog = integ_rpca_fun(merged_list_seurat_obj, length(merged_list_seurat_obj))
merged_list_seurat_obj_cc_rpcalog = integ_rpca_fun(merged_list_seurat_obj_cc, length(merged_list_seurat_obj_cc))

saveRDS(merged_list_seurat_obj_rpcalog, paste0(directory_output, "merged_list_seurat_obj_rpcalog.rds"))
saveRDS(merged_list_seurat_obj_cc_rpcalog, paste0(directory_output, "merged_list_seurat_obj_cc_rpcalog.rds"))

```

```{r, Integration RPCA on SCTransform normalisation}

integ_rpca_sct_fun = function(list_obj, number_conditions) {

  # choose RNA assay as default assay for each object
  for (i in 1:number_conditions) {DefaultAssay(list_obj[[i]]) = "SCT"}
  # select features that are repeatedly variable across datasets for integration
  features = SelectIntegrationFeatures(object.list = list_obj,
                                       nfeatures = 2000, 
                                       assay = rep("SCT", number_conditions),
                                       verbose = TRUE)
  # run PCA to be able to apply rpca for integration
  list_obj = lapply(X = list_obj, FUN = RunPCA, features = features)
  # identify anchors to integrate the datasets
  anchors = FindIntegrationAnchors(object.list = list_obj,
                                   assay = rep("SCT", number_conditions),
                                   anchor.features = features,
                                   normalization.method = "sct",
                                   reduction = "rpca",
                                   verbose = TRUE)
  # create an integrated data assay in the object
  list_obj = IntegrateData(anchorset = anchors, 
                           new.assay.name = "integrated.sct",
                           normalization.method = "sct",
                           verbose = TRUE)
  # return output
  return(list_obj)
  
}

merged_list_seurat_obj_rpcasct = integ_rpca_sct_fun(merged_list_seurat_obj, length(merged_list_seurat_obj))
merged_list_seurat_obj_cc_rpcasct = integ_rpca_sct_fun(merged_list_seurat_obj_cc, length(merged_list_seurat_obj_cc))

saveRDS(merged_list_seurat_obj_rpcasct, paste0(directory_output, "merged_list_seurat_obj_rpcasct.rds"))
saveRDS(merged_list_seurat_obj_cc_rpcasct, paste0(directory_output, "merged_list_seurat_obj_cc_rpcasct.rds"))


```

```{r, Integration CCA based on LogNormalization}

# Normalize and identify features for each dataset independently => already done
integ_cca_fun = function(list_obj, number_conditions) {

  # choose RNA assay as default assay for each object
  for (i in 1:number_conditions) {DefaultAssay(list_obj[[i]]) = "RNA"}
  # select features that are repeatedly variable across datasets for integration
  features = SelectIntegrationFeatures(object.list = list_obj,
                                       nfeatures = 2000, 
                                       assay = rep("RNA", number_conditions),
                                       verbose = TRUE)
  # identify anchors to integrate the datasets
  anchors = FindIntegrationAnchors(object.list = list_obj,
                                   assay = rep("RNA", number_conditions),
                                   anchor.features = features,
                                   normalization.method = "LogNormalize",
                                   reduction = "cca",
                                   verbose = TRUE)
  # create an integrated data assay in the object
  list_obj = IntegrateData(anchorset = anchors, 
                           new.assay.name = "integrated.log",
                           normalization.method = "LogNormalize",
                           verbose = TRUE)
  # return output
  return(list_obj)
  
}

merged_list_seurat_obj_cca = integ_cca_fun(merged_list_seurat_obj, number_conditions)
merged_list_seurat_obj_cc_cca = integ_cca_fun(merged_list_seurat_obj_cc, number_conditions)

saveRDS(merged_list_seurat_obj_cc_cca, paste0(directory_output, "merged_list_seurat_obj_cc_cca.rds"))
saveRDS(merged_list_seurat_obj_cca, paste0(directory_output, "merged_list_seurat_obj_cca.rds"))

```

```{r, Integration CCA based on SCTransform normalization}


integ_sct_fun = function(list_obj, number_conditions) {
  
  # choose SCT assay as default assay for each object
  for (i in 1:number_conditions) {DefaultAssay(list_obj[[i]]) = "SCT"}
  # select features that are repeatedly variable across datasets for integration
  features = SelectIntegrationFeatures(object.list = list_obj,
                                       nfeatures = 2000, 
                                       assay = rep("SCT", number_conditions),
                                       verbose = TRUE)
  # prepare the object for integration
  list_obj = PrepSCTIntegration(object.list = list_obj,
                                assay = rep("SCT", number_conditions),
                                anchor.features = features,
                                verbose = TRUE)
  
  # identify anchors to integrate the datasets
  anchors = FindIntegrationAnchors(object.list = list_obj,
                                   assay = rep("SCT", number_conditions),
                                   anchor.features = features,
                                   normalization.method = "SCT",
                                   reduction = "cca",
                                   verbose = TRUE)
  # create an integrated data assay in the object
  list_obj = IntegrateData(anchorset = anchors, 
                           new.assay.name = "integrated.sct",
                           normalization.method = "SCT",
                           verbose = TRUE)
  # return output
  return(list_obj)
  
}

merged_list_seurat_obj_cca_sct = integ_sct_fun(merged_list_seurat_obj, number_conditions)
merged_list_seurat_obj_cc_cca_sct = integ_sct_fun(merged_list_seurat_obj_cc, number_conditions)

saveRDS(merged_list_seurat_obj_cca_sct, paste0(directory_output, "merged_list_seurat_obj_cca_sct.rds"))
saveRDS(merged_list_seurat_obj_cc_cca_sct, paste0(directory_output, "merged_list_seurat_obj_cc_cca_sct.rds"))

```

```{r, Visualize, fig.width = 16, fig.height = 16}

merged_list_seurat_obj_rpcalog = ScaleData(merged_list_seurat_obj_rpcalog) %>%
  RunPCA(merged_list_seurat_obj_rpcalog, npcs = 30) %>%
  RunUMAP(merged_list_seurat_obj_rpcalog, reduction = "pca", dims = 1:30)
p1 <- DimPlot(merged_list_seurat_obj_rpcalog, reduction = "umap", group.by = "orig.ident")
p2 <- DimPlot(merged_list_seurat_obj_rpcalog, reduction = "umap", split.by = "orig.ident")
p3 <- DimPlot(merged_list_seurat_obj_rpcalog, reduction = "pca", group.by = "orig.ident")
p4 <- DimPlot(merged_list_seurat_obj_rpcalog, reduction = "pca", split.by = "orig.ident")
p1 | p2
p3 | p4

```


```{r, Save outputs}

# saveRDS(integ_seurat_obj_cc_log, paste0(directory_output, "integratelog_seurat_obj_qc_norm_ccr.rds"))
# saveRDS(integ_seurat_obj_log, paste0(directory_output, "integratelog_seurat_obj_qc_norm.rds"))

saveRDS(integ_seurat_obj_cc_sct, paste0(directory_output, "integratesct_seurat_obj_qc_norm_ccr.rds"))
saveRDS(integ_seurat_obj_sct, paste0(directory_output, "integratesct_seurat_obj_qc_norm.rds"))

```

```{r, Rsession}

# Clean working space and show package version
# rm(list = ls())
# sessionInfo()

```





